# Gradio Dockerfile
FROM python:3.11.10-slim

ENV PYTHONUNBUFFERED=1
ENV OMP_NUM_THREADS=1

# Set working directory
WORKDIR /app

# Copy app files
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Expose port
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

# Command to run the Gradio app
CMD ["gradio", "app.py"]
# CMD ["python", "app.py"]